[package]
  cjc-version = "1.0.5"
  compile-option = "-O2 --int-overflow=wrapping --experimental --enable-eh -Woff unused"
  description = ""
  name = "restest_runner"
  output-type = "executable"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"

[dependencies]
  restest_common = { path = "../restest_common", output-type = "static" }
  __RESTEST_TARGET_PACKAGE_NAME__ = { path = "__RESTEST_TARGET_PACKAGE_PATH__", output-type = "static" }

[package.package-configuration."restest_runner.deps"]
  output-type = "static"

[package.package-configuration.restest_runner]
  compile-option = "--link-options \"__RESTEST_TARGET_ARCHIVE_PATH__\""

[package.package-configuration."restest_runner.macros"]
  compile-option = "--link-options \"target/release/restest_runner/librestest_runner.deps.a\""

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["${CANGJIE_STDX_PATH}/linux_x86_64_cjnative/dynamic/stdx"]
